#!/usr/bin/env bash
# scripts/gen_idl.sh
#
# Generate Fast-DDS type support from an IDL file using Fast-DDS-Gen.
# Outputs go into: ./generated/<idl_file_basename>/
# fastddsgen typically writes files under: ./generated/<idl>/src/idl/
# Also writes: ./generated/<idl>/idl_gen.env
#
# Usage:
#   ./scripts/gen_idl.sh <path/to/file.idl> [out_dir]
#
# Env overrides:
#   FASTDDSGEN_ROOT   Path to Fast-DDS-Gen repo (default: ~/Fast-DDS-Gen)
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<EOF
Usage:
  $0 <path/to/file.idl> [out_dir]

Defaults:
  out_dir = generated/<idl_file_basename>/

Env:
  FASTDDSGEN_ROOT   Path to Fast-DDS-Gen repo (default: ~/Fast-DDS-Gen)
EOF
}

log() { printf "\n\033[1;34m==> %s\033[0m\n" "$*"; }
die() { printf "\n\033[1;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

if [[ $# -lt 1 || "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit 0
fi

IDL_IN_RAW="$1"
OUT_DIR_RAW="${2:-}"

IDL_IN="$IDL_IN_RAW"
if [[ "$IDL_IN" != /* ]]; then
  IDL_IN="${ROOT_DIR}/${IDL_IN}"
fi
[[ -f "${IDL_IN}" ]] || die "IDL file not found: ${IDL_IN}"

IDL_FILE_BASE="$(basename "${IDL_IN}" .idl)"

if [[ -z "${OUT_DIR_RAW}" ]]; then
  OUT_DIR="${ROOT_DIR}/generated/${IDL_FILE_BASE}"
else
  OUT_DIR="${OUT_DIR_RAW}"
  if [[ "${OUT_DIR}" != /* ]]; then
    OUT_DIR="${ROOT_DIR}/${OUT_DIR}"
  fi
fi

: "${FASTDDSGEN_ROOT:=$HOME/Fast-DDS-Gen}"
SCRIPTS_DIR="${FASTDDSGEN_ROOT}/scripts"
FASTDDSGEN_BIN="${SCRIPTS_DIR}/fastddsgen"

[[ -d "${FASTDDSGEN_ROOT}" ]] || die "Fast-DDS-Gen root not found: ${FASTDDSGEN_ROOT}"
[[ -x "${FASTDDSGEN_BIN}" ]] || die "fastddsgen not found/executable at: ${FASTDDSGEN_BIN}
Hint: build it first:
  cd ${FASTDDSGEN_ROOT} && ./gradlew assemble"

mkdir -p "${OUT_DIR}"
export PATH="${SCRIPTS_DIR}:$PATH"

LOG_FILE="${OUT_DIR}/fastddsgen.log"
log "fastddsgen: ${FASTDDSGEN_BIN}"
log "IDL:      ${IDL_IN}"
log "OUT:      ${OUT_DIR}"
log "LOG:      ${LOG_FILE}"

# Run generator and capture stdout/stderr
set +e
fastddsgen -d "${OUT_DIR}" "${IDL_IN}" >"${LOG_FILE}" 2>&1
RC=$?
set -e
if [[ $RC -ne 0 ]]; then
  echo "---- fastddsgen output (tail) ----" >&2
  tail -n 200 "${LOG_FILE}" >&2 || true
  die "fastddsgen failed with exit code ${RC}. See: ${LOG_FILE}"
fi

# Infer the first struct name (your HelloMsg). Useful for app semantics, not filenames.
TYPE_BASENAME="$(
  grep -E '^[[:space:]]*struct[[:space:]]+[A-Za-z_][A-Za-z0-9_]*' -m 1 "${IDL_IN}" \
  | sed -E 's/^[[:space:]]*struct[[:space:]]+([A-Za-z_][A-Za-z0-9_]*).*/\1/'
)"
[[ -n "${TYPE_BASENAME}" ]] || TYPE_BASENAME="${IDL_FILE_BASE}"

# Detect where generated headers actually live
GEN_IDL_DIR="${OUT_DIR}/src/idl"
if [[ ! -d "${GEN_IDL_DIR}" ]]; then
  echo "---- fastddsgen output (tail) ----" >&2
  tail -n 200 "${LOG_FILE}" >&2 || true
  die "fastddsgen succeeded but did not create expected directory: ${GEN_IDL_DIR}"
fi

# Confirm we actually have generated sources
if [[ -z "$(find "${GEN_IDL_DIR}" -type f -name "*PubSubTypes.*" | head -n 1)" ]]; then
  echo "---- fastddsgen output (tail) ----" >&2
  tail -n 200 "${LOG_FILE}" >&2 || true
  die "fastddsgen reported success but no *PubSubTypes.* files were generated under: ${GEN_IDL_DIR}"
fi

# Generated basename for filenames is typically the IDL file basename (Hello.idl -> Hello.hpp)
GEN_BASENAME="${IDL_FILE_BASE}"

ENV_FILE="${OUT_DIR}/idl_gen.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/gen_idl.sh
export IPCBENCH_IDL_FILE="${IDL_IN}"
export IPCBENCH_IDL_FILE_BASE="${IDL_FILE_BASE}"
export IPCBENCH_IDL_TYPE_BASENAME="${TYPE_BASENAME}"

# Where fastddsgen actually wrote the generated headers/sources:
export IPCBENCH_GENERATED_DIR="${OUT_DIR}"
export IPCBENCH_GENERATED_IDL_DIR="${GEN_IDL_DIR}"

# Basename for generated filenames (Hello.hpp / HelloPubSubTypes.hpp / etc.)
export IPCBENCH_GEN_BASENAME="${GEN_BASENAME}"
EOF

log "Wrote: ${ENV_FILE}"
log "Type (struct) basename: ${TYPE_BASENAME}"
log "Generated IDL dir:      ${GEN_IDL_DIR}"
log "Generated file basename: ${GEN_BASENAME}"

log "Generated files (sample):"
find "${GEN_IDL_DIR}" -type f | sort | head -n 50
